Update README.md
wptide/wptide pull request #183
Opened 2019-04-19 09:28 UTC by Chintesh

Documentation updated.

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions.

### Description of the Change

### Alternate Designs

### Benefits

### Possible Drawbacks

### Verification Process

### Applicable Issues

2019-04-22 15:48 UTC, jeffpaul requested changes
See inline changes needed

2019-04-22 15:48 UTC, jeffpaul commented on README.md
> +| `API_ADMIN_PASSWORD` | The password associated with the local admin account. Default is `WordPress`. |
This is an incorrect change as the password is case sensitive, please revert.

2019-04-22 15:48 UTC, jeffpaul commented on README.md
> +To make local development simple we have added default values for the `API_KEY` and `API_SECRET` associated with the `audit-server` user, which will automatically update the user meta values when `ma
This is an incorrect change as the command is `make` and not `making`, please revert.

2019-05-14 20:16 UTC, jeffpaul commented
@Chintesh are you able to make the updates that I noted?

2019-05-21 08:25 UTC, valendesigns commented
@Chintesh Thank you for bringing this to our attention. I've updated the typo in the `develop` branch. The other two changes were not correct. I want you to know that we appreciate your contribution, but a simple text change will not get anyone contributor status. I have to manually change several files to add a contributor and then deploy everything to App Engine. It's a lot of effort for such a small thing. If you want to get added to the list it will have to be an important text change or actual code contribution. Thank you though, and I hope you still want to contribute and help the project.

2019-05-21 08:25 UTC, closed without merging